# Generated by Django 5.0.6 on 2024-05-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_director_genre_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
